### ISSUE TITLE
Implement SASL Authentication.

### ISSUE THREAD

**Issue by pefoley2** [watchtower/asyncirc#1]

**Comment by ZacharyDuBois** [comment]
This is not needed in our bot setup as our bot will be connecting through a local ZNC instance. Maybe in the future.

**Comment by pefoley2** [comment]
Well, @fwilson42 said that he'd implement features needed for https://github.com/tjcsl/cslbot, so I'd leave this open for now :)

**Comment by ZacharyDuBois** [comment]
Well, see what happens when you leave a blank description :) Miscommunication. I'll leave it for @fwilson42 then.

**Comment by fwilson42** [comment]
This will be implemented as `watchtower.plugins.cap` and `watchtower.plugins.sasl`.

**Comment by pefoley2** [comment]
You'll probably also need plugins.authenticate

**Comment by fwilson42** [comment]
nope!

Anyway, asyncirc.plugins.sasl works now. SASL is supported
